services:
  postgres-server:
    container_name: zabbix-postgres
    image: timescale/timescaledb:2.10.0-pg14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TS_TUNE_MAX_CONNS: 70
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:7.0.9-ol
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 3
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      PHP_TZ: ${PHP_TZ}
      ZBX_VALUECACHESIZE: 2G
      ZBX_CACHESIZE: 2G
      ZBX_STARTPOLLERS: 50
      ZBX_STARTPREPROCESSORS: 50
      ZBX_HISTORYCACHESIZE: 512M
      ZBX_HISTORYINDEXCACHESIZE: 64M
      ZBX_TRENDCACHESIZE: 64M
      ZBX_STARTHTTPPOLLERS: 40
    depends_on:
      - postgres-server
    volumes:
      - ./alertscripts:/usr/lib/zabbix/alertscripts
      - ./externalscripts:/usr/lib/zabbix/externalscripts
    networks:
      - zabbix-net

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:7.0.0-ol
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      ZBX_UPLOADMAXFILESIZE: 5M
      PHP_TZ: ${PHP_TZ}
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 8081:8080
    networks:
      - zabbix-net

  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.0
    user: "0"
    restart: unless-stopped
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=dashboardNewLayouts,useV2DashboardsAPI,kubernetesFeatureToggles,kubernetesDashboards,kubernetesClientDashboardsFolders,kubernetesClientDashboardsFolders
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
    ports:
      - 8082:3000
    volumes:
      - ./grafana/dados:/var/lib/grafana
    networks:
      - zabbix-net

volumes:
  pgdata:

networks:
  zabbix-net:
