version: '3.1'
services:
  postgres-server:
    image: timescale/timescaledb:2.10.0-pg14
    restart: always
    ports:
      - 57919:5432
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: alqqnx728469ACRIML
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data
      TS_TUNE_MAX_CONNS: 70
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  zabbix-server:
    #build:
    #  dockerfile: Dockerfile-zabbix-server-pgsql
    image: zabbix/zabbix-server-pgsql:6.4.3-ol
    restart: always
    environment: 
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: alqqnx728469ACRIML
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 3
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      PHP_TZ: "America/Sao_Paulo"
      ZBX_VALUECACHESIZE: 2G
      ZBX_CACHESIZE: 2G
      ZBX_STARTPOLLERS: 50
      ZBX_STARTPREPROCESSORS: 50
      ZBX_HISTORYCACHESIZE: 512M
      ZBX_HISTORYINDEXCACHESIZE: 64M
      ZBX_TRENDCACHESIZE: 64M
      ZBX_STARTHTTPPOLLERS: 40
    depends_on:
      - postgres-server
    volumes:
      - ./alertscripts:/usr/lib/zabbix/alertscripts
      - ./externalscripts:/usr/lib/zabbix/externalscripts

  zabbix-web: 
    image: zabbix/zabbix-web-nginx-pgsql:6.4.3-ol
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: alqqnx728469ACRIML
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      ZBX_UPLOADMAXFILESIZE: 5M
      PHP_TZ: "America/Sao_Paulo"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 57917:8080

  grafana:
    image:  grafana/grafana:10.0.1
    user: "0"
    restart: unless-stopped
    ports:
     - 57918:3000
    volumes:
#      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dados:/var/lib/grafana
